version: '3.8'
services:
  bot:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file: .env
    restart: always
    ports:
      - "8080:8080"